### ISSUE TITLE
view_model not rendering Cannot access renderRequested error

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-common-measures-gem#112]
@antoine-galataud was missed by CI since measure ran, but noticed when viewing html for another workflow. I thought maybe was specific to 3.4, but happens in 3.3 as well. Wondering if related to recent commit on this. Here is screenshot of console error on Chrome mac for the html made from unit test. I assume view_data may have same issue. 

![Screen Shot 2022-06-23 at 5 44 05 PM](https://user-images.githubusercontent.com/4857055/175433319-435a8be8-de35-4758-8d38-83b8fb9f40d6.png)

**Comment by antoine-galataud** [comment]
@DavidGoldwasser ok thanks, I’ll have a look asap.
