### ISSUE TITLE
Support OpenStudio 3.0

### ISSUE THREAD

**Issue by nllong** [NREL/openstudio-common-measures-gem#13]
Need to update version of Ruby and related libraries to support OpenStudio 3.0. This will require bumping the version of this gem to 0.2.x.

**Comment by DavidGoldwasser** [comment]
There are 100 tests that fail or error across 11 measures.  Here are the categories they fall into
- issues with standards gem changes (Matt D looking into)
- Intersect issue on create bar (see log below). This works on 2.9.1 and not 3.0. I don't think this is related to standards, could be ruby upgrade, or could be OpenStudio change.
- Radiance tests (not familiar with this measure, I'll look at this last)

-- example create bar log issue
[utilities.geometry.intersect] <1> Face difference is self intersecting, result will not include this polygon, [[4.572, 0, 0], [0, 4.572, 0], [55.6486, 4.572, 0], [54.9183, 3.84174, 0], [0.730266, 3.84173, 0]]
[openstudio.model.Surface] <1> Initial area of surface 'Surface 127' 233.522 does not equal post intersection area 193.417
[openstudio.model.Surface] <1> Initial area of other surface 'Surface 163' 102.708 does not equal post intersection area 296.125
[openstudio.model.Surface] <1> Initial area of other surface 'Surface 174' 8.05784 does not equal post intersection area 49.9698
measure results for rotation_45_party_wall_fraction

**Comment by DavidGoldwasser** [comment]
For create_bar_from_building_type_ratio I confirmed the intersection is for the 5 failures (out of 74 total tests). None of them fail in 2.9.1. There are known issues with intersection and I don't know that we can do anything about it now, but we should address as soon as we can. The work around for this if soeone hits in actual use it to bypass intersection by making mid story floors and ceilings adiabatic using argument below.
```
    args['make_mid_story_surfaces_adiabatic'] = true
```

**Comment by DavidGoldwasser** [comment]
The radiance measure issue seems like it isn't a real issue. I was running through system ruby instead of the openstudio CLI so I could  more easily use custom standards gem. The measures were failing to access output files used by the measure. When I went back to running the measure test through the CLI, it ran without any errors. CI will later will confirm this is still the case.
