### ISSUE TITLE
Push to rubygems

### ISSUE THREAD

**Issue by macumber** [NREL/openstudio-common-measures-gem#2]
- [ ] Check license and authors
- [ ] Tag release
- [ ] Push to rubygems

**Comment by tijcolem** [comment]
We have to wait until the main repository https://github.com/NREL/openstudio-measures is released before pushing this out. We have to copy changes from that repository to this. 

Eventually, the goal is to have all measures in one repository.

**Comment by tijcolem** [comment]
Closing. Part of the release process checklist. https://github.com/NREL/OpenStudio/issues/3526

**Comment by nllong** [comment]
This has been pushed with the new OpenStudio measures on 2/29/20

https://rubygems.org/gems/openstudio-common-measures
