### ISSUE TITLE
Fix Ventilaiton Report

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-common-measures-gem#28]
Confirm first if that is VentilationQAQC or if Ventilation Report is on a different repo
https://unmethours.com/question/46251/ventilation-report-measure/?answer=46282#post-id-46282

Looking at BCL, they appear to be the same
https://bcl.nrel.gov/node/84712

**Comment by DavidGoldwasser** [comment]
@asparke2 did you develop this measure? I had not worked on it.

**Comment by eringold** [comment]
I was looking at the version in OpenStudio-measures:
https://github.com/NREL/OpenStudio-measures/tree/develop/nrel_published/VentilationQAQC
But it's also located in (at least) openstudio-common-measures-gem:
https://github.com/NREL/openstudio-common-measures-gem/tree/develop/lib/measures/VentilationQAQC
which also has the deprecated methods:
https://github.com/NREL/openstudio-common-measures-gem/blob/343736912973bf2074bd31eb9f760ec7c7328646/lib/measures/VentilationQAQC/measure.rb#L239-L242

**Comment by DavidGoldwasser** [comment]
@eringold I'm negligent at merging this down, but this pull request removes all of the nrel_published measures that have been moved to public measure gem repos
https://github.com/NREL/OpenStudio-measures/pull/318

**Comment by asparke2** [comment]
@DavidGoldwasser I don't remember, but probably so.  I've got no availability to work on anything beside EULP and ComStock, so if this needs to get fixed someone who has time planned on OS will have to fix it.

**Comment by DavidGoldwasser** [comment]
Fixed by pull request #29
