### ISSUE TITLE
3.1.0 upgrade issues

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-common-measures-gem#35]
OpenStudio Results already has a few issues, this issue is a catchall for other measures that need updates for 3.1.0. Below is 9.18 run results for `openstudio measure -r` on local run on mac.

![Screen Shot 2020-09-21 at 9 16 10 AM](https://user-images.githubusercontent.com/4857055/93785273-21223e00-fbeb-11ea-90e9-f6dd9fecfb85.png)

Failures are on
- [ ] OpenStudio Results (see other issues)
- [x] ServerDirectoryCleanup
- [x] VentilationQAQC
- [ ] GenericQAQC

Errors are on 
- [ ] RadiantSlabWithQAQC

Details on failures and errors are described below, except for OpenStudioResults which is covered by other existing issues. Fixes will be made to 3_1_0_upgrade. May have to wait until CI is updated to merge to develop, but that might not be necessary.

**Comment by DavidGoldwasser** [comment]
**RadiantSlabWithDoas

- [ ] test_multi_zone_office_3C_ceiling** the error below was also seen on prototype/baseline/create_typical measures and may require fix to standards gem.

ArgumentError: comparison of FalseClass with 20 failed :/ruby/2.5.0/bundler/gems/openstudio-standards-b0cabd8c2fa8/lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb:417:in

- [ ] The other tree tests are erroring in this line (`assert(errs.empty?, errs.join("\n"))`) of the test with `errs` showing up as nil?

NoMethodError: undefined method `empty?' for nil:NilClass

**Comment by DavidGoldwasser** [comment]
- [ ] While I don't recall seeing it on earlier 3.1 tests, I'm seeing an error on View Data where a model is being forward translated to IDF and then reverse translated back to OSM. 
```ViewData_Test#test_ViewData_LastIDF_Timestep:
RuntimeError: Unknown OpenStudio Enum Value ''
    C:/Users/dgoldwas/Documents/GitHub/NREL/openstudio-common-measures-gem/lib/measures/view_data/measure.rb:212:in `translateWorkspace'
    C:/Users/dgoldwas/Documents/GitHub/NREL/openstudio-common-measures-gem/lib/measures/view_data/measure.rb:212:in `run'
    C:/Users/dgoldwas/Documents/GitHub/NREL/openstudio-common-measures-gem/lib/measures/view_data/tests/ViewData_Test.rb:311:in `test_ViewData_LastIDF_Timestep'```

@jmarrec and @kbenne could be good to test this with next alpha build. If I can isolate this to simple test and confirm the issue I can file an OpenStudio issue.

**Comment by jmarrec** [comment]
I would pinpoint exactly what's causing this. It seems that it's trying to reverse translate an object, and tries to construct an enum from a text value, except that text is `''` (empty). Any OpenStudio enum constructed with an empty string would fail with this message.

eg:

```
OpenStudio::EndUseFuelType.new('')
RuntimeError: Unknown OpenStudio Enum Value ''
```

**Comment by DavidGoldwasser** [comment]
@jmarrec I'll send IDF and OSM in Slack. I also filed OpenStudio Issue
https://github.com/NREL/OpenStudio/issues/4096

**Comment by DavidGoldwasser** [comment]
view_data fixed by fix for this OS issue https://github.com/NREL/OpenStudio/issues/4096. I made commit to measure anyway to update test OSM from 1.1.3 to 3.0.1

**Comment by DavidGoldwasser** [comment]
@jmarrec that commit did the trick. I ran both the test code above and the full measure test.
