### ISSUE TITLE
Issue with OpenStudio Results fenestration calculations

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-common-measures-gem#63]
This was pointed out by a user on[ UH with this post](https://unmethours.com/question/53323/why-does-openstudio-not-correctly-calculate-my-subsurface-area-size/) and as shown below I see issue with both windows and doors when comparing to the EnergyPlus table.

![Screen Shot 2021-03-22 at 2 35 09 PM](https://user-images.githubusercontent.com/4857055/112055433-74ceff00-8b1c-11eb-9cad-b09a915df125.png)

**Comment by eringold** [comment]
FYI: https://github.com/NREL/OpenStudio-measures/issues/320

**Comment by DavidGoldwasser** [comment]
@eringold thanks for pointing out that old issue, sorry I didn't catch that before. I'll make that change and a pull request here shortly.

**Comment by DavidGoldwasser** [comment]
Here is screenshot of test model (not same as above) after the fix. ft^2 on left m^2 on right

![Screen Shot 2021-03-22 at 3 22 38 PM](https://user-images.githubusercontent.com/4857055/112060205-7ef3fc00-8b22-11eb-9015-673b6599ebd2.png)
