### ISSUE TITLE
Tariff Selection-Flat measure needs to be updated for newer E+ versions

### ISSUE THREAD

**Issue by shorowit** [NREL/openstudio-common-measures-gem#65]
https://github.com/NREL/openstudio-common-measures-gem/blob/develop/lib/measures/tariff_selection_flat/measure.rb#L230

Should be "NaturalGas:Facility" for E+ 9.4. See https://unmethours.com/question/53476/why-are-my-openstudio-results-showing-different-utility-rates-than-my-tariff-measure-inputs/?answer=53621#post-id-53621

Might be worth auditing other measures for similar errors.

**Comment by erikkolderup** [comment]
This problem also applies to the measure, Tariff Selection - Time and Date Dependant"
