### ISSUE TITLE
update generic_qaqc for 90.1 2016 and 2019

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-common-measures-gem#79]
Add one test for each of this and also test with comstock versions of 90.1 if I'm going to dynamically generate standard choices from the extension gem.

- [x] dynamic generate choices from ext gem
- [x] add test for 2016
- [x] add test for 2019
- [x] add test for comstock version of 90.1 (or hide from possible choices)
- [x] Update report messages so 2013 isn't hard coded
- [x] update documentation (would be nice to include report screenshot)

**Comment by DavidGoldwasser** [comment]
Current EUI and end use reasonableness doesn't work with 2016, 2019 or ComStock templates. I've added message to indicate that if it returns nil. That can be removed if updated in the future.

**Comment by DavidGoldwasser** [comment]
- [ ] See why Mechanical System Efficiency is failing
- [ ] Investigate high target water usage volume.

**Comment by DavidGoldwasser** [comment]
mech sys eff seems to be failing here
https://github.com/NREL/openstudio-common-measures-gem/blob/develop/lib/measures/generic_qaqc/resources/check_mech_sys_efficiency.rb#L189

**Comment by DavidGoldwasser** [comment]
Boiler capacity is 0 which is causing method above to return false. So seems to be issue with model, but it could be nice to report out details in measure such as capacity, as that doesn't get printed with search criteria.

**Comment by DavidGoldwasser** [comment]
Fixed order of operations mistake on full service and quick service estimation fo number of meals. It had been over-estimating meals and SWH target for FSR, and under-estimating for QSR.

**Comment by DavidGoldwasser** [comment]
Not sure if I'll do it now, but at some point make checks that compare to prototype inputs what building type it is compared to. Decide if specific approach is appropriate  for mixed use buildings. Should mixed use be skipped, or created blended expected values. Right now some (EUI and end use) use primary building type, not sure what is done for service hot water.

**Comment by DavidGoldwasser** [comment]
Part load ratio lookup failed on UO example file. @mdahlhausen would you need more info to diagnose this.
`Didn't find chiller for 90.1-2013 WaterCooled Rotary Screw Chiller 0 1934tons 0.6kW/ton. {"template"=>"90.1-2013", "cooling_type"=>"WaterCooled", "compressor_type"=>"Rotary Screw"}`

**Comment by DavidGoldwasser** [comment]
Update message on system type check. It isn't really incorrect because use case isn't to make baseline model. I can update message, but maybe for non-baseline use should skip this check.

`Zone FullServiceRestaurant Kitchen B - Story Ground baseline system type is incorrect. Supposed to be VAV_Reheat, but was PSZ_AC instead`

**Comment by DavidGoldwasser** [comment]
try to extend summary table in report no what tolerances we used? maybe extra two columns for min/max, if add this make sure to add units.

**Comment by DavidGoldwasser** [comment]
- [ ] For baseline checks replace "expected value" with "baseline" value, here is one example

`U value of 0.47 (Btu/ft^2*h*R) for U 0.48 SHGC 0.40 Dbl Ref-D Clr 6mm/13mm in FullServiceRestaurant Dining - 90.1-2013 is more than 25.0 % below the expected value of 0.77 (Btu/ft^2*h*R) for ASHRAE 90.1-2013.`

U value of 0.47 (Btu/ft^2*h*R) for U 0.48 SHGC 0.40 Dbl Ref-D Clr 6mm/13mm in FullServiceRestaurant Dining - 90.1-2013 is more than 25.0 % below the expected value of 0.77 (Btu/ft^2*h*R) for ASHRAE 90.1-2013.
--


<br class="Apple-interchange-newline">

U value of 0.47 (Btu/ft^2*h*R) for U 0.48 SHGC 0.40 Dbl Ref-D Clr 6mm/13mm in FullServiceRestaurant Dining - 90.1-2013 is more than 25.0 % below the expected value of 0.77 (Btu/ft^2*h*R) for ASHRAE 90.1-2013.
--


<br class="Apple-interchange-newline">

**Comment by DavidGoldwasser** [comment]
- [ ] See if I can clear up this error when no rule of thumb for SWH. The two I have seen were blended space type models, before fix it confirm if happens on non blended model.

<img width="1237" alt="Screen Shot 2022-04-19 at 8 56 58 AM" src="https://user-images.githubusercontent.com/4857055/164033756-59b6f963-ae70-4aa4-8007-c360b6d64a88.png">

**Comment by mdahlhausen** [comment]
On the chiller lookup:
`Didn't find chiller for 90.1-2013 WaterCooled Rotary Screw Chiller 0 1934tons 0.6kW/ton.
{"template"=>"90.1-2013", "cooling_type"=>"WaterCooled", "compressor_type"=>"Rotary Screw"}`
This particular chiller has two options depending on the date.  Chillers installed after Jan 1, 2015 have a different efficiency requirement than those installed before that under 90.1-2013.  I'm wondering if this has something to do with the error.  The chiller data is in the data .json, so I'm not sure why it's not finding it.

**Comment by mdahlhausen** [comment]
"@mdahlhausen do you think there is any value in keeping this check enable for non-baseline use cases?"

no

**Comment by DavidGoldwasser** [comment]
- [ ] Investigate low target water for hotel The one below is from 300k sqft hotel
`Annual average of 10928 gallons per day of hot water is more than 50.0 % above the expected value of 2802 gallons per day`

**Comment by mdahlhausen** [comment]
More on the chiller stuff - I'm able to run the `chiller_electric_eir_apply_efficiency_and_curves` method and do the lookup with the same search criteria that isn't working for you.
One think is interesting is `Didn't find chiller for`.  That language never appears in openstudio-standards.  Instead the log message says `For #{chiller_electric_eir.name}, cannot find chiller properties`.  I'm wondering if that means this is on the measure side.
Also, the template rules still apply - you need to build the Standard object with the template you want to apply efficiency values for.

**Comment by DavidGoldwasser** [comment]
- [ ] Update envelope check so it uses actual standards construction type instead of hard coded values. This was throwing confusing warnings when I had model with mass wall but it was checking against value for steel frame wall. Also cleanup excess warnings that occur for every space type. Only reason for more than one space type is if one is residential and the other is non-residential.
https://github.com/NREL/openstudio-common-measures-gem/blob/qaqc_issue_79/lib/measures/generic_qaqc/resources/check_envelope_conductance.rb#L75-L81

**Comment by DavidGoldwasser** [comment]
Updating envelope took a lot of work to clean up and extend. In addition to use construction type, I use the space type to look at the building category (typically Nonresidential or Residential) which come with different target performance levels. So the same construction may trigger a message in one space, but not in another. 

There is still a lot of work that can be done to improve the current categories, and to add new ones. I would expect this measure to be active for the next few releases.
